#!/usr/bin/env bash
# Regenerates the Heimdall contract ABIs used by server/ and web/ from Foundry build output.
# ABIs are never hand-written (docs/instructions.md §4.2). Run after changing contracts:
#   bash scripts/gen-abi.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# Cloud sessions only; local machines use their own toolchain.
if [[ -f "$HOME/.heimdall-env" ]]; then source "$HOME/.heimdall-env"; fi
( cd "$ROOT/contracts" && forge build >/dev/null )
SRV="$ROOT/server/internal/chain/abi"
WEB="$ROOT/web/src/lib/abi"
mkdir -p "$SRV" "$WEB"
for c in HeimdallGuard HeimdallGuardFactory; do
  node -e 'const j=require(process.argv[1]); process.stdout.write(JSON.stringify(j.abi,null,2)+"\n")' \
    "$ROOT/contracts/out/$c.sol/$c.json" > "$SRV/$c.json"
  {
    echo "// Generated by scripts/gen-abi.sh from contracts/out/$c.sol/$c.json. Do not edit."
    printf 'export const %sAbi = ' "$(echo "${c:0:1}" | tr 'A-Z' 'a-z')${c:1}"
    cat "$SRV/$c.json" | sed '$ s/$/ as const;/'
  } > "$WEB/$c.ts"
done
# Test mocks (local plain-anvil development and the fork simulator's feed override only).
node -e 'const j=require(process.argv[1]); process.stdout.write(JSON.stringify({abi:j.abi,deployedBytecode:j.deployedBytecode.object},null,2)+"\n")' \
  "$ROOT/contracts/out/Mocks.sol/MockPriceFeed.json" > "$SRV/MockPriceFeed.json"
node -e 'const j=require(process.argv[1]); process.stdout.write(JSON.stringify(j.abi,null,2)+"\n")' \
  "$ROOT/contracts/out/Mocks.sol/MockLendingVault.json" > "$SRV/MockLendingVault.json"
echo "ABIs written to $SRV and $WEB"
