#!/usr/bin/env bash
# Local development on a plain anvil (chain id 31337, NO fork) with the test mocks from
# contracts/test/script/LocalDev.s.sol. This is for building and checking the app without an
# Arbitrum RPC. It is NOT the demo path: the demo runs on an Arbitrum One fork against real
# protocol contracts (scripts/demo-fork.sh).
#
#   bash scripts/local-dev.sh            start anvil if needed, deploy, write config/targets.local.json
#   bash scripts/local-dev.sh --fresh    stop the anvil this script started on the same port first (clean chain)
#   RPC_URL=http://127.0.0.1:8645 bash scripts/local-dev.sh   use another port (a second, independent stack)
#
# Then run the server with the env it prints.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
if [[ -f "$HOME/.heimdall-env" ]]; then source "$HOME/.heimdall-env"; fi
RPC="${RPC_URL:-http://127.0.0.1:8545}"
PORT="${RPC##*:}"; PORT="${PORT%%/*}"

# PUBLIC TEST KEY: anvil's well-known default account #9, used as the keeper on local chains only.
# It is published in anvil's docs and holds nothing of value. Never use it anywhere else.
ANVIL_KEY_9="0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"

if [[ "${1:-}" == "--fresh" ]]; then
  # only the anvil this script started on THIS port (other anvils keep running)
  pkill -f -- "--block-time 1 --port $PORT" 2>/dev/null || true
  sleep 1
fi
# Some npm-wrapped foundry builds exit 0 even when the node is unreachable, so check the output.
up() { [[ "$(cast chain-id --rpc-url "$RPC" 2>/dev/null)" =~ ^[0-9]+$ ]]; }
if ! up; then
  echo ">> starting anvil (block time 1s) on port $PORT"
  mkdir -p "$ROOT/.local"
  nohup anvil --block-time 1 --port "$PORT" >"$ROOT/.local/anvil.log" 2>&1 &
  for _ in $(seq 1 50); do up && break; sleep 0.2; done
fi
up || { echo "anvil is not reachable at $RPC (see .local/anvil.log)" >&2; exit 1; }

echo ">> deploying the local mocks and the Heimdall factory"
D="$ROOT/contracts/deployments/31337.json"
rm -f "$D"
( cd "$ROOT/contracts" && forge script test/script/LocalDev.s.sol --rpc-url "$RPC" --broadcast >/dev/null )
[[ -f "$D" ]] || { echo "LocalDev did not write $D (the deployment failed)" >&2; exit 1; }

jq -n --slurpfile d "$D" '
  $d[0] as $d | {
  chainId: 31337,
  note: "GENERATED by scripts/local-dev.sh from contracts/deployments/31337.json. Local test mocks only (not the demo path). Git-ignored.",
  aaveV3: { pool: { address: $d.aavePool, source: "MockAavePool deployed by contracts/test/script/LocalDev.s.sol (local only)" } },
  ethUsdFeed: { address: $d.ethUsdFeed, source: "MockPriceFeed (2,500 USD) deployed by LocalDev.s.sol (local only)" },
  targets: [
    { id: "mock-vault-usdc", label: "Mock lending vault (USDC)", protocol: "Mock", type: "ERC4626",
      address: $d.vault, source: "MockLendingVault deployed by LocalDev.s.sol (local only)",
      asset: $d.usdc, assetSymbol: "USDC", assetDecimals: 6, assetIsStable: true,
      signals: {
        marketFeed:    { address: $d.marketFeed,    source: "MockPriceFeed (local only)" },
        referenceFeed: { address: $d.referenceFeed, source: "MockPriceFeed (local only)" },
        collateralFeeds: [ { label: "xUSD", address: $d.collateralFeed, source: "MockPriceFeed (local only)" } ],
        liquidity: { mode: "idle", holder: $d.vault },
        watchContracts: [ { label: "Vault", address: $d.vault } ]
      },
      sim: { drainers: [ $d.crowd ], mockVault: true } },
    { id: "mock-aave-usdc", label: "Mock Aave V3 (USDC)", protocol: "Aave V3", type: "AAVE_V3",
      address: $d.usdc, source: "MockAavePool reserve for the mock USDC (local only)",
      aToken: $d.aToken, asset: $d.usdc, assetSymbol: "USDC", assetDecimals: 6, assetIsStable: true,
      signals: { liquidity: { mode: "idle" }, watchContracts: [] }, sim: {} }
  ],
  demo: { ada: $d.ada, ben: $d.ben, usdcSource: { address: "", source: "not needed on the local mock chain" } }
}' > "$ROOT/config/targets.local.json"
echo ">> wrote config/targets.local.json"

cat <<OUT

Local chain is ready. Run the server (from server/) with:

  export RPC_HTTP_URL=$RPC
  export DATABASE_URL=postgres://heimdall:heimdall@127.0.0.1:5432/heimdall?sslmode=disable
  export TARGETS_FILE=../config/targets.local.json
  export SIGNALS_FILE=../config/signals.json
  export DEPLOYMENT_FILE=../contracts/deployments/31337.json
  export KEEPER_PRIVATE_KEY=$ANVIL_KEY_9   # public anvil test key
  export DEMO_MODE=true
  go run ./cmd/heimdalld

Ada (anvil #1) = $(jq -r .ada "$D"), Ben (anvil #2) = $(jq -r .ben "$D")
Factory = $(jq -r .factory "$D")
OUT
