// Generated by scripts/gen-abi.sh from contracts/out/HeimdallGuardFactory.sol/HeimdallGuardFactory.json. Do not edit.
export const heimdallGuardFactoryAbi = [
	{
		type: 'constructor',
		inputs: [
			{
				name: 'aavePool_',
				type: 'address',
				internalType: 'address'
			},
			{
				name: 'admin_',
				type: 'address',
				internalType: 'address'
			},
			{
				name: 'keeper_',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'nonpayable'
	},
	{
		type: 'function',
		name: 'aavePool',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'admin',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'createGuard',
		inputs: [],
		outputs: [
			{
				name: 'guard',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'nonpayable'
	},
	{
		type: 'function',
		name: 'guardOf',
		inputs: [
			{
				name: 'owner',
				type: 'address',
				internalType: 'address'
			}
		],
		outputs: [
			{
				name: 'guard',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'implementation',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'isGuard',
		inputs: [
			{
				name: 'guard',
				type: 'address',
				internalType: 'address'
			}
		],
		outputs: [
			{
				name: '',
				type: 'bool',
				internalType: 'bool'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'keeper',
		inputs: [],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'keeperExitBatch',
		inputs: [
			{
				name: 'reqs',
				type: 'tuple[]',
				internalType: 'struct HeimdallGuardFactory.ExitRequest[]',
				components: [
					{
						name: 'guard',
						type: 'address',
						internalType: 'address'
					},
					{
						name: 'positionType',
						type: 'uint8',
						internalType: 'enum HeimdallGuard.PositionType'
					},
					{
						name: 'target',
						type: 'address',
						internalType: 'address'
					},
					{
						name: 'maxAmount',
						type: 'uint256',
						internalType: 'uint256'
					},
					{
						name: 'reasonHash',
						type: 'bytes32',
						internalType: 'bytes32'
					}
				]
			}
		],
		outputs: [],
		stateMutability: 'nonpayable'
	},
	{
		type: 'function',
		name: 'predictGuard',
		inputs: [
			{
				name: 'owner',
				type: 'address',
				internalType: 'address'
			}
		],
		outputs: [
			{
				name: '',
				type: 'address',
				internalType: 'address'
			}
		],
		stateMutability: 'view'
	},
	{
		type: 'function',
		name: 'setKeeper',
		inputs: [
			{
				name: 'newKeeper',
				type: 'address',
				internalType: 'address'
			}
		],
		outputs: [],
		stateMutability: 'nonpayable'
	},
	{
		type: 'function',
		name: 'transferAdmin',
		inputs: [
			{
				name: 'newAdmin',
				type: 'address',
				internalType: 'address'
			}
		],
		outputs: [],
		stateMutability: 'nonpayable'
	},
	{
		type: 'event',
		name: 'AdminChanged',
		inputs: [
			{
				name: 'previousAdmin',
				type: 'address',
				indexed: true,
				internalType: 'address'
			},
			{
				name: 'newAdmin',
				type: 'address',
				indexed: true,
				internalType: 'address'
			}
		],
		anonymous: false
	},
	{
		type: 'event',
		name: 'BatchExitResult',
		inputs: [
			{
				name: 'index',
				type: 'uint256',
				indexed: true,
				internalType: 'uint256'
			},
			{
				name: 'guard',
				type: 'address',
				indexed: true,
				internalType: 'address'
			},
			{
				name: 'target',
				type: 'address',
				indexed: true,
				internalType: 'address'
			},
			{
				name: 'success',
				type: 'bool',
				indexed: false,
				internalType: 'bool'
			},
			{
				name: 'amountOut',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256'
			},
			{
				name: 'err',
				type: 'bytes',
				indexed: false,
				internalType: 'bytes'
			}
		],
		anonymous: false
	},
	{
		type: 'event',
		name: 'GuardCreated',
		inputs: [
			{
				name: 'owner',
				type: 'address',
				indexed: true,
				internalType: 'address'
			},
			{
				name: 'guard',
				type: 'address',
				indexed: true,
				internalType: 'address'
			}
		],
		anonymous: false
	},
	{
		type: 'event',
		name: 'KeeperChanged',
		inputs: [
			{
				name: 'previousKeeper',
				type: 'address',
				indexed: true,
				internalType: 'address'
			},
			{
				name: 'newKeeper',
				type: 'address',
				indexed: true,
				internalType: 'address'
			}
		],
		anonymous: false
	},
	{
		type: 'error',
		name: 'FailedDeployment',
		inputs: []
	},
	{
		type: 'error',
		name: 'GuardExists',
		inputs: []
	},
	{
		type: 'error',
		name: 'InsufficientBalance',
		inputs: [
			{
				name: 'balance',
				type: 'uint256',
				internalType: 'uint256'
			},
			{
				name: 'needed',
				type: 'uint256',
				internalType: 'uint256'
			}
		]
	},
	{
		type: 'error',
		name: 'NotAdmin',
		inputs: []
	},
	{
		type: 'error',
		name: 'NotKeeper',
		inputs: []
	},
	{
		type: 'error',
		name: 'UnknownGuard',
		inputs: [
			{
				name: 'guard',
				type: 'address',
				internalType: 'address'
			}
		]
	},
	{
		type: 'error',
		name: 'ZeroAddress',
		inputs: []
	}
] as const;
