// Package chain wraps the Ethereum JSON-RPC client and the contract ABIs heimdalld needs.
package chain

import (
	"embed"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

// Heimdall ABIs are generated by scripts/gen-abi.sh from Foundry output; never hand-edit.
//
//go:embed abi/HeimdallGuard.json abi/HeimdallGuardFactory.json abi/MockLendingVault.json abi/MockPriceFeed.json
var abiFS embed.FS

func mustParse(js string) abi.ABI {
	a, err := abi.JSON(strings.NewReader(js))
	if err != nil {
		panic(fmt.Sprintf("bad ABI: %v", err))
	}
	return a
}

func embedded(name string) []byte {
	b, err := abiFS.ReadFile("abi/" + name)
	if err != nil {
		panic(err)
	}
	return b
}

var (
	GuardABI        = mustParse(string(embedded("HeimdallGuard.json")))
	FactoryABI      = mustParse(string(embedded("HeimdallGuardFactory.json")))
	MockVaultABI    = mustParse(string(embedded("MockLendingVault.json")))
	MockFeedABI     abi.ABI
	MockFeedRuntime []byte // deployed bytecode of MockPriceFeed (simulator only)
)

func init() {
	var f struct {
		ABI      json.RawMessage `json:"abi"`
		Deployed string          `json:"deployedBytecode"`
	}
	if err := json.Unmarshal(embedded("MockPriceFeed.json"), &f); err != nil {
		panic(err)
	}
	MockFeedABI = mustParse(string(f.ABI))
	b, err := hexutil.Decode(f.Deployed)
	if err != nil {
		panic(err)
	}
	MockFeedRuntime = b
}

// Third-party ABI fragments, written only from sources that were read:
//
//   - ERC20 / ERC4626: OpenZeppelin, contracts/lib/openzeppelin-contracts/contracts/
//     token/ERC20/IERC20.sol, token/ERC20/extensions/IERC20Metadata.sol, interfaces/IERC4626.sol
//   - Chainlink AggregatorV3Interface (decimals, latestRoundData): Chainlink Data Feeds API
//     reference https://docs.chain.link/data-feeds/api-reference ; the same shape is
//     implemented by MockPriceFeed in contracts/test/mocks/Mocks.sol.
//   - Aave V3 Pool getReserveData / supply: contracts/src/interfaces/IAavePool.sol
//     (copied there from aave-dao/aave-v3-origin IPool.sol and DataTypes.sol).
const erc20JSON = `[
 {"type":"function","name":"balanceOf","stateMutability":"view","inputs":[{"name":"account","type":"address"}],"outputs":[{"name":"","type":"uint256"}]},
 {"type":"function","name":"totalSupply","stateMutability":"view","inputs":[],"outputs":[{"name":"","type":"uint256"}]},
 {"type":"function","name":"decimals","stateMutability":"view","inputs":[],"outputs":[{"name":"","type":"uint8"}]},
 {"type":"function","name":"approve","stateMutability":"nonpayable","inputs":[{"name":"spender","type":"address"},{"name":"value","type":"uint256"}],"outputs":[{"name":"","type":"bool"}]},
 {"type":"function","name":"transfer","stateMutability":"nonpayable","inputs":[{"name":"to","type":"address"},{"name":"value","type":"uint256"}],"outputs":[{"name":"","type":"bool"}]}
]`

const erc4626JSON = `[
 {"type":"function","name":"asset","stateMutability":"view","inputs":[],"outputs":[{"name":"assetTokenAddress","type":"address"}]},
 {"type":"function","name":"totalAssets","stateMutability":"view","inputs":[],"outputs":[{"name":"totalManagedAssets","type":"uint256"}]},
 {"type":"function","name":"convertToAssets","stateMutability":"view","inputs":[{"name":"shares","type":"uint256"}],"outputs":[{"name":"assets","type":"uint256"}]},
 {"type":"function","name":"convertToShares","stateMutability":"view","inputs":[{"name":"assets","type":"uint256"}],"outputs":[{"name":"shares","type":"uint256"}]},
 {"type":"function","name":"maxWithdraw","stateMutability":"view","inputs":[{"name":"owner","type":"address"}],"outputs":[{"name":"maxAssets","type":"uint256"}]},
 {"type":"function","name":"maxRedeem","stateMutability":"view","inputs":[{"name":"owner","type":"address"}],"outputs":[{"name":"maxShares","type":"uint256"}]},
 {"type":"function","name":"deposit","stateMutability":"nonpayable","inputs":[{"name":"assets","type":"uint256"},{"name":"receiver","type":"address"}],"outputs":[{"name":"shares","type":"uint256"}]},
 {"type":"function","name":"redeem","stateMutability":"nonpayable","inputs":[{"name":"shares","type":"uint256"},{"name":"receiver","type":"address"},{"name":"owner","type":"address"}],"outputs":[{"name":"assets","type":"uint256"}]}
]`

const aggregatorJSON = `[
 {"type":"function","name":"decimals","stateMutability":"view","inputs":[],"outputs":[{"name":"","type":"uint8"}]},
 {"type":"function","name":"latestRoundData","stateMutability":"view","inputs":[],"outputs":[
   {"name":"roundId","type":"uint80"},{"name":"answer","type":"int256"},{"name":"startedAt","type":"uint256"},
   {"name":"updatedAt","type":"uint256"},{"name":"answeredInRound","type":"uint80"}]}
]`

// getReserveData returns a fully static struct (15 words, layout in IAavePool.sol). The output is
// declared as bytes only so the fragment parses; AaveReserve decodes the raw return data word by word.
const aavePoolJSON = `[
 {"type":"function","name":"supply","stateMutability":"nonpayable","inputs":[{"name":"asset","type":"address"},{"name":"amount","type":"uint256"},{"name":"onBehalfOf","type":"address"},{"name":"referralCode","type":"uint16"}],"outputs":[]},
 {"type":"function","name":"getReserveData","stateMutability":"view","inputs":[{"name":"asset","type":"address"}],"outputs":[{"name":"","type":"bytes"}]}
]`

var (
	ERC20ABI      = mustParse(erc20JSON)
	ERC4626ABI    = mustParse(erc4626JSON)
	AggregatorABI = mustParse(aggregatorJSON)
	AavePoolABI   = mustParse(aavePoolJSON)
)

// S6 event signatures (docs/api.md §4). Topic 0 is the keccak256 of the signature.
var S6Signatures = []string{
	"OwnershipTransferred(address,address)",
	"Upgraded(address)",
	"AdminChanged(address,address)",
	"Paused(address)",
	"Unpaused(address)",
}
